name = "PEAK"
author = "Artea"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9fafb3fa966485e007a631cc59feff85771bb2b942a39ff86d40abd70546c0c3"

[versions]
minecraft = "1.21.8"
neoforge = "21.8.49"
